language: ruby
cache: bundler

sudo: false

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7

gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile

before_script:
  - bundle exec rake -f spec/dummy/Rakefile db:schema:load
